
DROP DATABASE IF EXISTS cgi_example;
CREATE DATABASE cgi_example;

CREATE TABLE cgi_example.submission (
	id INT(11) NOT NULL AUTO_INCREMENT,
	fname VARCHAR(256) NOT NULL DEFAULT "",
	lname VARCHAR(256) NOT NULL DEFAULT "",
	address1 VARCHAR(1024) NOT NULL DEFAULT "",
	address2 VARCHAR(1024) NOT NULL DEFAULT "",
	city VARCHAR(256) NOT NULL DEFAULT "",
	state VARCHAR(2) NOT NULL DEFAULT "",
	PRIMARY KEY (id)
) Engine = InnoDB, CHARACTER SET utf8;
